const NODE_CLASSNAME = {
  Button: '.yu-button',
  Checkbox: '.yu-checkbox-group',
  Counter: '.yu-counter',
  CounterSide: '.yu-counter-side',
  Input: '.yu-input',
  Radio: '.yu-radio-group',
  Select: '.yu-select',
  Cascader: '.yu-cascader',
  Switch: '.yu-switch',
  Slider: '.yu-slider',
  DatePicker: '.yu-date-picker',
  FileList: '.yu-file-list',
  Rate: '.yu-rate',
  Field: '.yu-field',
  Table: '.yu-table',
  Tag: '.yu-tag',
  Progress: '.yu-progress',
  Pagination: '.yu-pagination',
  Badge: '.yu-badge',
  Alert: '.yu-alert',
  Loading: '.yu-loading',
  Message: '.yu-message',
  Notification: '.yu-notification',
  Dialog: '.yu-dialog',
  Tooltip: '.yu-tooltip',
  Tabs: '.yu-tabs',
  Breadcrumb: '.yu-breadcrumb',
  Steps: '.yu-steps',
  Collapse: '.yu-collapse',
}

export default NODE_CLASSNAME
